[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#in insertmode and using ctrl+shift+v or middle-click,
#automatically :set paste
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_char = '¦'
'''

#trailing whitespace to be highlighted in red and remove
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'tpope/vim-fugitive'

#check syntax
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  let g:ale_sign_column_always = 1
  let g:ale_cpp_gcc_options = "-std=c++17 -Wall"
  nmap <silent> <C-k> <Plug>(ale_previous_wrap)
  nmap <silent> <C-j> <Plug>(ale_next_wrap)
  let g:ale_linters = {
\    'c++':['g++']
\  }
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:NERDTreeDirArrows = 1
  let g:NERDTreeDirArrowExpandable  = '→'
  let g:NERDTreeDirArrowCollapsible = '↓'
  " ctrl-n で NERDTree を起動
  nnoremap <silent> <C-n> :NERDTreeToggle<CR>
  " autocmd vimenter * if !argc() | NERDTree | endif
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''

#run commands and show its result quickly
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = {
  \  "_" : {
  \    "hook/time/enable" : 1,
  \    "outputter/buffer/close_on_empty" : 1
  \  },
  \  "python" : {
  \    "type" : "python",
  \    "command" : "python3",
  \  },
  \  "cpp" : {
  \    "cmdopt" : "-std=c++11"
  \  }
  \}
  command! ZQuickrun :QuickRun -input =@+
'''

#help you read complex code by showing diff level of parentheses in diff color
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'let g:rainbow_active = 1'

#fuzzy finder in vim
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'set rtp+=~/.fzf'

#show a git diff in the sign column
[[plugins]]
repo = 'airblade/vim-gitgutter'






[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = 'colorscheme onedark'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
  let g:airline_theme = 'deus'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo =  'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'
hook_add = 'let g:vimfiler_as_default_explorer = 1'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = 'vmap <Enter> <Plug>(EasyAlign)'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'


